const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'../confirmed.html'),'utf8'),script=fs.readFileSync(path.join(__dirname,'../.github/scripts/confirmation.js'),'utf8');
async function page(hash,invalid=false){let calls=[],options;const dom=new JSDOM(html,{url:'https://losstudio.github.io/LOS-app/confirmed.html'+hash,runScripts:'outside-only'}),w=dom.window;w.supabase={createClient:(url,key,opts)=>{options=opts;return {auth:{setSession:async()=>invalid?{error:{}}:{data:{session:{user:{id:'same-account'}}}},getUser:async()=>({data:{user:{id:'same-account'}}}),updateUser:async attrs=>{calls.push(attrs);return {}},signOut:async opts=>{calls.push(opts);return {}}}}}};await w.eval(script);return {dom,w,calls,options};}
(async()=>{let p=await page('#type=recovery&access_token=test&refresh_token=test');assert.equal(p.options.auth.persistSession,false);assert.equal(p.w.location.hash,'');assert.equal(p.w.document.querySelector('form').hidden,false);p.w.document.getElementById('reset-new-password').value='new-password';p.w.document.getElementById('reset-confirm-password').value='different';p.w.document.querySelector('form').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,10));assert.equal(p.calls.length,0);p.w.document.getElementById('reset-confirm-password').value='new-password';p.w.document.querySelector('form').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,10));assert.deepEqual(p.calls.map(x=>JSON.parse(JSON.stringify(x))),[{password:'new-password'},{scope:'global'}]);assert(p.w.document.querySelector('h1').textContent.includes('successfully'));p.dom.window.close();
 p=await page('#type=recovery&access_token=test&refresh_token=test',true);assert(p.w.document.querySelector('form').hidden);p.dom.window.close();
 p=await page('#error=access_denied&type=recovery');assert(p.w.document.querySelector('form').hidden);assert.equal(p.w.location.hash,'');p.dom.window.close();
 p=await page('#type=email_change&access_token=test&refresh_token=test');assert(p.w.document.querySelector('h1').textContent.includes('updated successfully'));assert(p.w.document.querySelector('form').hidden);p.dom.window.close();
 p=await page('#type=signup&access_token=test');assert(p.w.document.querySelector('h1').textContent.includes('confirmed successfully'));assert(p.w.document.querySelector('form').hidden);p.dom.window.close();
 console.log('Password validation, token cleanup, invalid links, email-change and signup confirmations passed');})();
